//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj_son.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac_kayit
    {
        public string plaka { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string durum { get; set; }
        public string yakit { get; set; }
        public string vites { get; set; }
        public Nullable<decimal> ucret { get; set; }
    }
}
