//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj_son.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class car_rental_dbEntities : DbContext
    {
        public car_rental_dbEntities()
            : base("name=car_rental_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arac_kayit> arac_kayits { get; set; }
        public virtual DbSet<kiralama> kiralama { get; set; }
        public virtual DbSet<musteri> musteris { get; set; }
        public virtual DbSet<arac_iade> arac_iades { get; set; }
    }
}
