//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj_son.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public int tc { get; set; }
        public string ad_soyad { get; set; }
        public string adres { get; set; }
        public Nullable<int> telefon { get; set; }
        public string ehliyet { get; set; }
    }
}
